<?php



	$collections = $block->getCollection();
// echo "<pre>";
    // print_r($collections->getData());die;
// die;


// foreach($collections as $collection){
    // print_r($collection->getData());

// }die;

    if ($collections->count() > 0) {
?>
<div class="table-wrapper orders-history">
    <a href="/test/index/index">New Record</a>
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col id"><?php echo __('Id') ?></th>
            <th scope="col" class="col name"><?php echo __('Name') ?></th>
            <th scope="col" class="col email"><?php echo __('Email') ?></th>
            <th scope="col" class="col telephone"><?php echo __('Telephone') ?></th>
            <th scope="col" class="col Action"><?php echo __('Action') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
		foreach ($collections as $item): ?>
        <tr>
            <td data-th="<?= $block->escapeHtml(__('Id')) ?>" class="col id">
                <?php echo $item->getId() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Name')) ?>" class="col email">
                <?php echo $item->getEmail() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('email')) ?>" class="col Title">
                <?php echo $item->getName() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('telephone')) ?>" class="col author">
                <?php echo $item->getName() ?>
            </td>       
            <td data-th="<?= $block->escapeHtml(__('Action')) ?>" class="col delete">
                <a href="<?php echo $block->getDeleteAction() . 'id/' . $item->getId(); ?>">
                <?php echo __('Delete') ?></a>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php
	}
	?>