<button><a href="http://local.magento.com/crud/index/index/">Back to home</a></button>
<?php
 $collection = $block->getCollection();
if ($collection->count()) {
?>
<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?php echo __('curd_table') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col id"><?php echo __('id') ?></th>
            <th scope="col" class="col name"><?php echo __('Name') ?></th>
            <th scope="col" class="col email"><?php echo __('Email') ?></th>
            <th scope="col" class="col action"><?php echo __('Action') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
 foreach ($collection as $item): ?>
        <tr>
            <td data-th="<?= $block->escapeHtml(__('id')) ?>" class="col id">
                <?php echo $item->getId() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('name')) ?>" class="col name">
                <?php echo $item->getName() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('email')) ?>" class="col email">
                <?php echo $item->getEmail() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Action')) ?>" class="col delete">
                <a href="<?php echo $block->getDeleteAction() . 'id/' . $item->getId(); ?>"><?php echo __('Delete') ?></a>
                <a style="margin-left: 9px" href="<?php echo $block->getEditAction() . 'id/' . $item->getId(); ?>"><?php echo __('Edit') ?></a>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php
 }
 ?>